package enigma

// Rotors
const RotorI = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
const RotorII = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
const RotorIII = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
const RotorIV = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
const RotorV = "VZBRGITYUPSDNHLXAWMJQOFECK"
const RotorVI = "JPGVOUMFYQBENHZRDKASXLICTW"
const RotorVII = "NZJHGRCXMYSWBOUFAIVLPEKQDT"
const RotorVIII = "FKQHTLXOCBJSPDZRAMEWNIUYGV"

// Notches
const NotchI = 16
const NotchII = 4
const NotchIII = 21
const NotchIV = 9
const NotchV = 25

// Reflectors
const ReflectorA = "EJMZALYXVBWFCRQUONTSPIKHGD"
const ReflectorB = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
const ReflectorC = "FVPJIAOYEDRZXWGCTKUQSBNMHL"
